// Placeholder — regenerated by `npm run db:types` once the local
// Supabase stack is running and migrations are applied. Do not hand-edit
// this file once it's generated; hand-edit only this placeholder.

export type Database = Record<string, unknown>;
